export enum MODE {
  ENCRYPT = "ENCRYPT",
  DECRYPT = "DECRYPT"
}

export enum TYPE {
  STANDARD_VIGENERE = "STANDARD VIGENERE",
  FULL_VIGENERE = "FULL VIGENERE",
  EXTENDED_VIGENERE = "EXTENDED VIGENERE",
  AUTO_KEY_VIGENERE = "AUTO KEY VIGENERE",
  AFFINE = "AFFINE",
  PLAYFAIR = "PLAYFAIR",
  HILLL = "HILL"
}